version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck: # Añadido un healthcheck para asegurar que la DB esté lista
      test: ["CMD-SHELL", "pg_isready -U user -d mydatabase"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    # IMPORTANTE: Este es el placeholder que el pipeline reemplazará con tu usuario de Docker Hub
    image: samuelmorales/ci-cd-flask-app:latest 
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: production
      DATABASE_URL: postgresql://user:password@db:5432/mydatabase
    depends_on:
      db:
        condition: service_healthy # Espera a que la DB esté saludable
        
volumes:
  db_data: